version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get -y update
      - apt-get -y install jq
  pre_build:
    commands:
      - echo "Starting docker daemon..."
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "Logging into Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7)"
      - MD5="$(cat Cargo.lock | sed '/name = "{{project-name}}"/!b;n;cversion = "1.0.0"' | md5sum | awk '{print $1;}')"
      - VERSION="$(cat Cargo.toml | grep '^version.*' | sed -E 's/.*"(.*)"/\1/')"
  build:
    commands:
      - docker-compose -f docker-compose.aws.yml up -d mongo
      - echo "*** TEST ***"
      - echo "Attempting to pull test image tagged with $MD5"
      - scripts/build_test.sh
      - docker run --network rust-{{project-name}}_service -v $(pwd):/build "${REPOSITORY_URI}-test:$MD5" /build/scripts/test.sh
      - scripts/package.sh
reports:
  tests:
    files:
      - "**/*"
    base-directory: test-results
    discard-paths: yes
    file-format: JunitXml
