version: "3"
services:
  {{project-name}}:
    image: {{project-name}}:latest
    ports:
      - 8084:8000
    environment:
      PORT: 8000
      API_BASE: http://localhost:8084
      MONGO_URL: mongodb://mongo:27017/
      MONGO_DB_NAME: {{project-name}}
      RUST_LOG: info,surf=warn,actix_web=info
      BASE_PATH: {{project-name}}
      VERSION: v1
      CERTS: https://www.googleapis.com/oauth2/v2/certs
      DISABLE_AUTH: 1
    networks:
      - service
  mongo:
    image: mongo:latest
    ports:
      - 27084:27017
    networks:
      - service
networks:
  service:
    driver: bridge